'use client';

import { useState, useEffect } from 'react';

interface VideoPlayerProps {
  playId: number;
  gameId: string;
  sceneDescription?: string;
}

export default function VideoPlayer({ playId, gameId, sceneDescription }: VideoPlayerProps) {
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [elapsedTime, setElapsedTime] = useState(0);

  // Check if video exists when play changes
  useEffect(() => {
    setLoading(true);
    setError(null);
    checkVideoExists();
  }, [playId, gameId]);

  const checkVideoExists = async () => {
    try {
      const response = await fetch(`/api/game-analysis/generate-video?playId=${playId}&gameId=${gameId}`);
      const data = await response.json();
      if (data.exists) {
        setVideoUrl(data.videoUrl);
      } else {
        setVideoUrl(null);
      }
    } catch (err) {
      console.error('Error checking video:', err);
      setVideoUrl(null);
    } finally {
      setLoading(false);
    }
  };

  const generateVideo = async () => {
    setGenerating(true);
    setError(null);
    setProgress(0);
    setElapsedTime(0);

    // Track elapsed time
    const startTime = Date.now();
    const timeInterval = setInterval(() => {
      setElapsedTime(Math.floor((Date.now() - startTime) / 1000));
    }, 1000);

    // Simulate progress (Veo takes 1-3 minutes)
    const progressInterval = setInterval(() => {
      setProgress(p => {
        // Slow down as we approach 90%
        if (p < 30) return p + 1;
        if (p < 60) return p + 0.5;
        if (p < 85) return p + 0.2;
        return Math.min(p + 0.1, 90);
      });
    }, 1000);

    try {
      const response = await fetch('/api/game-analysis/generate-video', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          playId,
          gameId,
          sceneDescription,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setProgress(100);
        setVideoUrl(data.videoUrl);
      } else {
        setError(data.error || 'Failed to generate video');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Network error');
    } finally {
      clearInterval(progressInterval);
      clearInterval(timeInterval);
      setGenerating(false);
    }
  };

  const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return mins > 0 ? `${mins}m ${secs}s` : `${secs}s`;
  };

  if (loading) {
    return (
      <div className="aspect-video bg-slate-900/50 rounded-lg flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {videoUrl ? (
        <div className="space-y-4">
          {/* Video Player */}
          <div className="relative aspect-video bg-black rounded-lg overflow-hidden shadow-2xl">
            <video
              key={videoUrl}
              controls
              autoPlay
              loop
              className="w-full h-full object-contain"
            >
              <source src={videoUrl} type="video/mp4" />
              Your browser does not support video playback.
            </video>
            
            {/* Veo Badge */}
            <div className="absolute top-3 right-3 px-2 py-1 bg-black/60 backdrop-blur-sm rounded text-xs text-white flex items-center gap-1">
              <span className="text-purple-400">✦</span>
              Generated by Veo 3.1
            </div>
          </div>

          {/* Regenerate button */}
          <button
            onClick={generateVideo}
            disabled={generating}
            className="w-full px-4 py-2.5 bg-slate-700/50 hover:bg-slate-600/50 border border-slate-600 text-white rounded-lg font-medium transition-all disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {generating ? (
              <>
                <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Regenerating...
              </>
            ) : (
              <>
                <span>🔄</span>
                Regenerate Video
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {/* No video - show generate button or generation state */}
          <div className="aspect-video bg-gradient-to-br from-slate-900 to-slate-800 rounded-lg flex flex-col items-center justify-center border border-slate-700/50">
            {generating ? (
              <div className="text-center px-6 w-full max-w-md">
                {/* Animated Icon */}
                <div className="w-20 h-20 mb-6 mx-auto relative">
                  <div className="absolute inset-0 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 opacity-20 animate-ping"></div>
                  <div className="relative w-full h-full rounded-full bg-gradient-to-r from-blue-600 to-purple-600 flex items-center justify-center">
                    <span className="text-3xl">🎬</span>
                  </div>
                </div>
                
                <h4 className="text-white font-semibold text-lg mb-2">Generating with Veo 3.1</h4>
                <p className="text-slate-400 text-sm mb-6">
                  Creating AI-powered tactical coaching film...
                </p>
                
                {/* Progress bar */}
                <div className="w-full h-2 bg-slate-700 rounded-full overflow-hidden mb-3">
                  <div 
                    className="h-full bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-500 ease-out"
                    style={{ width: `${progress}%` }}
                  />
                </div>
                
                <div className="flex justify-between text-xs text-slate-500">
                  <span>{progress.toFixed(0)}% complete</span>
                  <span>{formatTime(elapsedTime)} elapsed</span>
                </div>
                
                <p className="text-xs text-slate-500 mt-4">
                  Typically takes 1-2 minutes
                </p>
              </div>
            ) : error ? (
              <div className="text-center px-6">
                <div className="w-16 h-16 mb-4 mx-auto rounded-full bg-red-500/10 flex items-center justify-center">
                  <span className="text-3xl">⚠️</span>
                </div>
                <h4 className="text-red-400 font-medium mb-2">Generation Failed</h4>
                <p className="text-slate-400 text-sm mb-6 max-w-xs">{error}</p>
                <button
                  onClick={generateVideo}
                  className="px-6 py-2.5 bg-red-600 hover:bg-red-500 text-white rounded-lg font-medium transition-all"
                >
                  Try Again
                </button>
              </div>
            ) : (
              <div className="text-center px-6">
                <div className="w-20 h-20 mb-6 mx-auto rounded-full bg-gradient-to-br from-blue-600/20 to-purple-600/20 flex items-center justify-center border border-slate-700">
                  <span className="text-4xl">🎥</span>
                </div>
                <h4 className="text-white font-semibold text-lg mb-2">No Video Generated</h4>
                <p className="text-slate-400 text-sm mb-6 max-w-xs">
                  Generate an AI-powered tactical coaching video for this play
                </p>
                <button
                  onClick={generateVideo}
                  className="px-8 py-3 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white rounded-lg font-medium transition-all shadow-lg shadow-purple-500/20 flex items-center gap-2 mx-auto"
                >
                  <span>✨</span>
                  Generate Video with Veo
                </button>
              </div>
            )}
          </div>

          {/* Info text */}
          {!generating && !error && (
            <div className="bg-slate-800/30 rounded-lg p-3 border border-slate-700/50">
              <p className="text-xs text-slate-400 text-center">
                <span className="text-purple-400">✦</span> Videos are generated using Google Veo 3.1 AI based on tactical scene descriptions
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
